version: '3.8'

services:
  # Our custom web app
  ticket-creator:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./context:/app/context
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/create-ticket
    depends_on:
      - n8n
    networks:
      - ticket-network

  # N8N for workflow management
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-workflows:/home/node/.n8n/workflows
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
    networks:
      - ticket-network

volumes:
  n8n_data:

networks:
  ticket-network:
    driver: bridge